### ISSUE TITLE
miui 6 mail app

### ISSUE THREAD

**Issue by ymg2006** [kqstone/ImmersedStatusBar#1]
mail app status bar is like this and cant create xml file to change it .
![screenshot_2015-05-31-00-55-31](https://cloud.githubusercontent.com/assets/844238/7899298/e08403c2-0732-11e5-99ae-b011073062ed.png)

**Comment by zdunex25** [comment]
Make a profile: https://github.com/watcgfw/ISBpreferences

**Comment by proudh0n** [comment]
zdunex25 could you explain int a bit? I don't understand chinese. Many thanks
